### ISSUE TITLE
Tooltipster unmaintained and JQuery EOL

### ISSUE THREAD

**Issue by pedroyzkrak** [obecker/decycle#79]
Hi! Before everything great work :)

Just a question: Have you had any thoughts on replacing tooltipster with anything else (e.g. https://github.com/atomiks/tippyjs)? Since it's unmaintained in quite some time now and uses an old version of JQuery that brings CVEs (e.g. https://nvd.nist.gov/vuln/detail/cve-2015-9251). Thanks!

**Comment by obecker** [comment]
Hi, thanks for your interest in decycle! 

Actually, I don't really understand your concern. Tooltipster is a jquery plugin, and it is working with the current jquery version (3.7.1). So the decycle report doesn't use any old jquery version. As long as Tooltipster is working with the latest jquery versions and as long as there are no other issues in Tooltipster, I don't see a need to replace it.

Do I miss something?

**Comment by nightm4re94** [comment]
If I may interject here, there are several outdated jquery references in tooltipster:

- [jQuery UI 1.11.4](https://releases.jquery.com/ui/) is referenced [here](https://github.com/calebjacob/tooltipster/blob/master/doc/js/jquery-ui-draggable/jquery-ui.js#L33), [here](https://github.com/calebjacob/tooltipster/blob/master/doc/js/jquery-ui-draggable/jquery-ui.js#L877), [here](https://github.com/calebjacob/tooltipster/blob/master/doc/js/jquery-ui-draggable/jquery-ui.js#L1058), and [here](https://github.com/calebjacob/tooltipster/blob/master/doc/js/jquery-ui-draggable/jquery-ui.min.js), introducing the following CVEs:
  - [CVE-2021-41182](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-41182)
  - [CVE-2021-41183](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-41183)
  - [CVE-2021-41184](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-41184)
  - [CVE-2022-31160](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2022-31160)
- [jQuery 1.10.2](https://releases.jquery.com/jquery/) is referenced [here](https://github.com/calebjacob/tooltipster/blob/master/doc/js/jquery-ui-draggable/external/jquery/jquery.js#L49), introducing the following CVEs:
  - [CVE-2015-9251](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-9251)
  - [CVE-2019-11358](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-11358)
  - [CVE-2020-11022](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-11022)
  - [CVE-2020-11023](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-11023)

Since we can probably not expect an update to tooltipster, considering alternatives is a valid suggestion IMHO.
Any project that applies decycle will generate CVE alerts when scanned e.g. with [Dependency-Check-Gradle](https://github.com/dependency-check/dependency-check-gradle).

**Comment by obecker** [comment]
Okay, I see what you mean. The OWASP dependency check reports these vulnerabilities. Decycle depends on the tooltipster webjar, which includes also jQuery 1.10.2 and jQuery UI 1.11.4. However, Decycle doesn't use these dependencies. So in the end this is a false positive report. I'll check what to do about it.

**Comment by nightm4re94** [comment]
One straightforward alternative would probably be to raise a PR in tooltipster that upgrades these dependency versions.

**Comment by obecker** [comment]
In my opinion this is rather an issue of the webjar, since both dependencies (jQuery and jQuery UI) are in the `doc` folder of the packed resources. I.e. the webjar contains the documentation and examples for tooltipster, which use outdated jQuery versions.

**Comment by obecker** [comment]
So I'm currently thinking about replacing or repacking the webjar ...

**Comment by nightm4re94** [comment]
Bravo, maestro 👏 Thanks for the fix.
